{"uuid": "7ac8c45a-12a1-4f61-b26a-a98b257f6ef1", "children": ["c1f9025d-9fb4-4724-a5ef-a77bc8d967f4"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\vzhuh\\config\\config_param.py\", line 67, in browser\n    driver = webdriver.Firefox(service=service, options=options_f)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 69, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Lena\\PycharmProjects\\pythonProjectgiiiiiiiiiiit\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1712081519124, "stop": 1712081524459}], "start": 1712081519124, "stop": 1712081524843}